//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERecall {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERecall.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGA RECALLS.
        /// </summary>
        public static string Feeds_MegaRecall_L {
            get {
                return ResourceManager.GetString("Feeds_MegaRecall_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT.
        /// </summary>
        public static string Feeds_Recent_L {
            get {
                return ResourceManager.GetString("Feeds_Recent_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRENDING.
        /// </summary>
        public static string Feeds_Trending_L {
            get {
                return ResourceManager.GetString("Feeds_Trending_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string SignInUP_ConfPass_PH {
            get {
                return ResourceManager.GetString("SignInUP_ConfPass_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string SignInUP_Email_PH {
            get {
                return ResourceManager.GetString("SignInUP_Email_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SignInUP_Email2_PH {
            get {
                return ResourceManager.GetString("SignInUP_Email2_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string SignInUP_Login_B {
            get {
                return ResourceManager.GetString("SignInUP_Login_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SignInUP_Name_PH {
            get {
                return ResourceManager.GetString("SignInUP_Name_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SignInUP_Pass_PH {
            get {
                return ResourceManager.GetString("SignInUP_Pass_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string SignInUP_SelCon_PH {
            get {
                return ResourceManager.GetString("SignInUP_SelCon_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    LOG IN   .
        /// </summary>
        public static string SignInUP_SignIn_L {
            get {
                return ResourceManager.GetString("SignInUP_SignIn_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    SIGN UP   .
        /// </summary>
        public static string SignInUP_SignUp_L {
            get {
                return ResourceManager.GetString("SignInUP_SignUp_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept eRecall Terms of Use and Privacy Policy.
        /// </summary>
        public static string SignInUP_TermsCond_L {
            get {
                return ResourceManager.GetString("SignInUP_TermsCond_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string SignInUP_ZipCode_PH {
            get {
                return ResourceManager.GetString("SignInUP_ZipCode_PH", resourceCulture);
            }
        }
    }
}
