// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CMO {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CMO.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LAapleSarkar {
            get {
                return ResourceManager.GetString("LAapleSarkar", resourceCulture);
            }
        }
        
        internal static string LBiography {
            get {
                return ResourceManager.GetString("LBiography", resourceCulture);
            }
        }
        
        internal static string LCabinetMinister {
            get {
                return ResourceManager.GetString("LCabinetMinister", resourceCulture);
            }
        }
        
        internal static string LChiefJustice {
            get {
                return ResourceManager.GetString("LChiefJustice", resourceCulture);
            }
        }
        
        internal static string LCmInternshipProgram {
            get {
                return ResourceManager.GetString("LCmInternshipProgram", resourceCulture);
            }
        }
        
        internal static string LCmOffice {
            get {
                return ResourceManager.GetString("LCmOffice", resourceCulture);
            }
        }
        
        internal static string LCmReliefsFund {
            get {
                return ResourceManager.GetString("LCmReliefsFund", resourceCulture);
            }
        }
        
        internal static string LCmVisits {
            get {
                return ResourceManager.GetString("LCmVisits", resourceCulture);
            }
        }
        
        internal static string LCollectors {
            get {
                return ResourceManager.GetString("LCollectors", resourceCulture);
            }
        }
        
        internal static string LContactcmo {
            get {
                return ResourceManager.GetString("LContactcmo", resourceCulture);
            }
        }
        
        internal static string LDigitalMaharashtra {
            get {
                return ResourceManager.GetString("LDigitalMaharashtra", resourceCulture);
            }
        }
        
        internal static string LDroughtFreeMaharashtra {
            get {
                return ResourceManager.GetString("LDroughtFreeMaharashtra", resourceCulture);
            }
        }
        
        internal static string LEvents {
            get {
                return ResourceManager.GetString("LEvents", resourceCulture);
            }
        }
        
        internal static string LForeignVisits {
            get {
                return ResourceManager.GetString("LForeignVisits", resourceCulture);
            }
        }
        
        internal static string LFormercmo {
            get {
                return ResourceManager.GetString("LFormercmo", resourceCulture);
            }
        }
        
        internal static string LGallery {
            get {
                return ResourceManager.GetString("LGallery", resourceCulture);
            }
        }
        
        internal static string LGovernor {
            get {
                return ResourceManager.GetString("LGovernor", resourceCulture);
            }
        }
        
        internal static string LGovtDepartment {
            get {
                return ResourceManager.GetString("LGovtDepartment", resourceCulture);
            }
        }
        
        internal static string LHome {
            get {
                return ResourceManager.GetString("LHome", resourceCulture);
            }
        }
        
        internal static string LInitiatives {
            get {
                return ResourceManager.GetString("LInitiatives", resourceCulture);
            }
        }
        
        internal static string LJalyuktaVisits {
            get {
                return ResourceManager.GetString("LJalyuktaVisits", resourceCulture);
            }
        }
        
        internal static string LJoinUs {
            get {
                return ResourceManager.GetString("LJoinUs", resourceCulture);
            }
        }
        
        internal static string LMagazineGallery {
            get {
                return ResourceManager.GetString("LMagazineGallery", resourceCulture);
            }
        }
        
        internal static string LMaharashtraVisits {
            get {
                return ResourceManager.GetString("LMaharashtraVisits", resourceCulture);
            }
        }
        
        internal static string LMakeInMaharashtra {
            get {
                return ResourceManager.GetString("LMakeInMaharashtra", resourceCulture);
            }
        }
        
        internal static string LNewsGallery {
            get {
                return ResourceManager.GetString("LNewsGallery", resourceCulture);
            }
        }
        
        internal static string LPersonalWebsite {
            get {
                return ResourceManager.GetString("LPersonalWebsite", resourceCulture);
            }
        }
        
        internal static string LPhotoGallery {
            get {
                return ResourceManager.GetString("LPhotoGallery", resourceCulture);
            }
        }
        
        internal static string LPressGallery {
            get {
                return ResourceManager.GetString("LPressGallery", resourceCulture);
            }
        }
        
        internal static string LRightToService {
            get {
                return ResourceManager.GetString("LRightToService", resourceCulture);
            }
        }
        
        internal static string LSecretaries {
            get {
                return ResourceManager.GetString("LSecretaries", resourceCulture);
            }
        }
        
        internal static string LSkillDevelopment {
            get {
                return ResourceManager.GetString("LSkillDevelopment", resourceCulture);
            }
        }
        
        internal static string LSocialResponsibilityCell {
            get {
                return ResourceManager.GetString("LSocialResponsibilityCell", resourceCulture);
            }
        }
        
        internal static string LStateMinisters {
            get {
                return ResourceManager.GetString("LStateMinisters", resourceCulture);
            }
        }
        
        internal static string LSwachhMaharashtra {
            get {
                return ResourceManager.GetString("LSwachhMaharashtra", resourceCulture);
            }
        }
        
        internal static string LTeamcmo {
            get {
                return ResourceManager.GetString("LTeamcmo", resourceCulture);
            }
        }
        
        internal static string LTeamMaharashtra {
            get {
                return ResourceManager.GetString("LTeamMaharashtra", resourceCulture);
            }
        }
        
        internal static string LTheChiefMinister {
            get {
                return ResourceManager.GetString("LTheChiefMinister", resourceCulture);
            }
        }
        
        internal static string LVideoGallery {
            get {
                return ResourceManager.GetString("LVideoGallery", resourceCulture);
            }
        }
        
        internal static string LVisionMissionOath {
            get {
                return ResourceManager.GetString("LVisionMissionOath", resourceCulture);
            }
        }
        
        internal static string LChangeLanguage {
            get {
                return ResourceManager.GetString("LChangeLanguage", resourceCulture);
            }
        }
        
        internal static string LContactEmail {
            get {
                return ResourceManager.GetString("LContactEmail", resourceCulture);
            }
        }
        
        internal static string LContactMobileNumber {
            get {
                return ResourceManager.GetString("LContactMobileNumber", resourceCulture);
            }
        }
        
        internal static string LContactName {
            get {
                return ResourceManager.GetString("LContactName", resourceCulture);
            }
        }
        
        internal static string LEmailCheck {
            get {
                return ResourceManager.GetString("LEmailCheck", resourceCulture);
            }
        }
        
        internal static string LMessage {
            get {
                return ResourceManager.GetString("LMessage", resourceCulture);
            }
        }
        
        internal static string LSubject {
            get {
                return ResourceManager.GetString("LSubject", resourceCulture);
            }
        }
        
        internal static string LSubmit {
            get {
                return ResourceManager.GetString("LSubmit", resourceCulture);
            }
        }
        
        internal static string LMenuChiefMinister {
            get {
                return ResourceManager.GetString("LMenuChiefMinister", resourceCulture);
            }
        }
        
        internal static string LMenuPhotoGallery {
            get {
                return ResourceManager.GetString("LMenuPhotoGallery", resourceCulture);
            }
        }
        
        internal static string LMenuPressRelease {
            get {
                return ResourceManager.GetString("LMenuPressRelease", resourceCulture);
            }
        }
        
        internal static string LMenuVideoGallery {
            get {
                return ResourceManager.GetString("LMenuVideoGallery", resourceCulture);
            }
        }
        
        internal static string LSearch {
            get {
                return ResourceManager.GetString("LSearch", resourceCulture);
            }
        }
        
        internal static string LPhotos {
            get {
                return ResourceManager.GetString("LPhotos", resourceCulture);
            }
        }
        
        internal static string LVideos {
            get {
                return ResourceManager.GetString("LVideos", resourceCulture);
            }
        }
        
        internal static string LCMOfficeAddress {
            get {
                return ResourceManager.GetString("LCMOfficeAddress", resourceCulture);
            }
        }
        
        internal static string LCMOfficeContactUsSubmitButton {
            get {
                return ResourceManager.GetString("LCMOfficeContactUsSubmitButton", resourceCulture);
            }
        }
        
        internal static string LCMOfficeEmail {
            get {
                return ResourceManager.GetString("LCMOfficeEmail", resourceCulture);
            }
        }
        
        internal static string LCMOfficeFaxNumber {
            get {
                return ResourceManager.GetString("LCMOfficeFaxNumber", resourceCulture);
            }
        }
        
        internal static string LCMOfficeName {
            get {
                return ResourceManager.GetString("LCMOfficeName", resourceCulture);
            }
        }
        
        internal static string LCMOfficePhoneNumber1 {
            get {
                return ResourceManager.GetString("LCMOfficePhoneNumber1", resourceCulture);
            }
        }
        
        internal static string LInitiativesTitle {
            get {
                return ResourceManager.GetString("LInitiativesTitle", resourceCulture);
            }
        }
        
        internal static string LComingSoon {
            get {
                return ResourceManager.GetString("LComingSoon", resourceCulture);
            }
        }
        
        internal static string LPressRelease {
            get {
                return ResourceManager.GetString("LPressRelease", resourceCulture);
            }
        }
        
        internal static string LMaharashtraVisitPhotos {
            get {
                return ResourceManager.GetString("LMaharashtraVisitPhotos", resourceCulture);
            }
        }
        
        internal static string LSomethingWentWrong {
            get {
                return ResourceManager.GetString("LSomethingWentWrong", resourceCulture);
            }
        }
        
        internal static string LWebserverNotResponding {
            get {
                return ResourceManager.GetString("LWebserverNotResponding", resourceCulture);
            }
        }
        
        internal static string LNoInternetConnection {
            get {
                return ResourceManager.GetString("LNoInternetConnection", resourceCulture);
            }
        }
        
        internal static string LNoRecordsFound {
            get {
                return ResourceManager.GetString("LNoRecordsFound", resourceCulture);
            }
        }
        
        internal static string LError {
            get {
                return ResourceManager.GetString("LError", resourceCulture);
            }
        }
        
        internal static string LExitApp {
            get {
                return ResourceManager.GetString("LExitApp", resourceCulture);
            }
        }
        
        internal static string LNo {
            get {
                return ResourceManager.GetString("LNo", resourceCulture);
            }
        }
        
        internal static string LOk {
            get {
                return ResourceManager.GetString("LOk", resourceCulture);
            }
        }
        
        internal static string LYes {
            get {
                return ResourceManager.GetString("LYes", resourceCulture);
            }
        }
        
        internal static string LExit {
            get {
                return ResourceManager.GetString("LExit", resourceCulture);
            }
        }
        
        internal static string LOf {
            get {
                return ResourceManager.GetString("LOf", resourceCulture);
            }
        }
        
        internal static string LDownloadFile {
            get {
                return ResourceManager.GetString("LDownloadFile", resourceCulture);
            }
        }
        
        internal static string LNotification {
            get {
                return ResourceManager.GetString("LNotification", resourceCulture);
            }
        }
        
        internal static string LThankYouMsg {
            get {
                return ResourceManager.GetString("LThankYouMsg", resourceCulture);
            }
        }
        
        internal static string LMessageLengthCheck {
            get {
                return ResourceManager.GetString("LMessageLengthCheck", resourceCulture);
            }
        }
        
        internal static string LMobileNumberCheck {
            get {
                return ResourceManager.GetString("LMobileNumberCheck", resourceCulture);
            }
        }
        
        internal static string LNameLengthCheck {
            get {
                return ResourceManager.GetString("LNameLengthCheck", resourceCulture);
            }
        }
        
        internal static string LSubjectLengthCheck {
            get {
                return ResourceManager.GetString("LSubjectLengthCheck", resourceCulture);
            }
        }
        
        internal static string LFieldIsRequired {
            get {
                return ResourceManager.GetString("LFieldIsRequired", resourceCulture);
            }
        }
        
        internal static string LCMOfficePhoneNumber2 {
            get {
                return ResourceManager.GetString("LCMOfficePhoneNumber2", resourceCulture);
            }
        }
        
        internal static string LCall {
            get {
                return ResourceManager.GetString("LCall", resourceCulture);
            }
        }
        
        internal static string LDialNumber {
            get {
                return ResourceManager.GetString("LDialNumber", resourceCulture);
            }
        }
        
        internal static string LMenu {
            get {
                return ResourceManager.GetString("LMenu", resourceCulture);
            }
        }
        
        internal static string LChiefMinisterDescription {
            get {
                return ResourceManager.GetString("LChiefMinisterDescription", resourceCulture);
            }
        }
        
        internal static string LChiefMinisterName {
            get {
                return ResourceManager.GetString("LChiefMinisterName", resourceCulture);
            }
        }
        
        internal static string LCMVisitDescription {
            get {
                return ResourceManager.GetString("LCMVisitDescription", resourceCulture);
            }
        }
        
        internal static string LTeamMaharashtraDescription {
            get {
                return ResourceManager.GetString("LTeamMaharashtraDescription", resourceCulture);
            }
        }
        
        internal static string LApplicationList {
            get {
                return ResourceManager.GetString("LApplicationList", resourceCulture);
            }
        }
        
        internal static string LMagazineGalleryJune2015 {
            get {
                return ResourceManager.GetString("LMagazineGalleryJune2015", resourceCulture);
            }
        }
        
        internal static string LMaharashtraAhead {
            get {
                return ResourceManager.GetString("LMaharashtraAhead", resourceCulture);
            }
        }
        
        internal static string LJoinUsDescription {
            get {
                return ResourceManager.GetString("LJoinUsDescription", resourceCulture);
            }
        }
        
        internal static string LNewsUpdates {
            get {
                return ResourceManager.GetString("LNewsUpdates", resourceCulture);
            }
        }
        
        internal static string LTheChiefMinisterTitle {
            get {
                return ResourceManager.GetString("LTheChiefMinisterTitle", resourceCulture);
            }
        }
        
        internal static string LCmVisitsTitle {
            get {
                return ResourceManager.GetString("LCmVisitsTitle", resourceCulture);
            }
        }
        
        internal static string LTeamMaharashtraTitle {
            get {
                return ResourceManager.GetString("LTeamMaharashtraTitle", resourceCulture);
            }
        }
        
        internal static string LPhotoGalleryTitle {
            get {
                return ResourceManager.GetString("LPhotoGalleryTitle", resourceCulture);
            }
        }
        
        internal static string LVideoGalleryTitle {
            get {
                return ResourceManager.GetString("LVideoGalleryTitle", resourceCulture);
            }
        }
        
        internal static string LNewsUpdatesTitle {
            get {
                return ResourceManager.GetString("LNewsUpdatesTitle", resourceCulture);
            }
        }
        
        internal static string LJoinUsTitle {
            get {
                return ResourceManager.GetString("LJoinUsTitle", resourceCulture);
            }
        }
        
        internal static string LNetworkError {
            get {
                return ResourceManager.GetString("LNetworkError", resourceCulture);
            }
        }
    }
}
